CREATE TABLE products
(
    id            int PRIMARY KEY,
    name          varchar(255),
    product_group varchar(255),
    price         float
);


CREATE TABLE products_in_vending_machine
(
    id                int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_entity_id int,
    amount            INT,
    FOREIGN KEY (product_entity_id) REFERENCES products (id)
);
